#!/usr/bin/env bash
set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")/../.." && pwd)"

AIDER_CONF="$HOME/.aider.conf.yml"
AIDER_SETTINGS="$HOME/.aider.model.settings.yml"
AIDER_METADATA="$HOME/.aider.model.metadata.json"
EXAMPLE_CONF="$SCRIPT_DIR/config/aider_conf.example.yml"
SRC_SETTINGS="$SCRIPT_DIR/config/aider.model.settings.yml"
SRC_METADATA="$SCRIPT_DIR/config/aider.model.metadata.json"
ENV_FILE="$SCRIPT_DIR/.env"
BIN_DIR="$HOME/.local/bin"

BOLD='\033[1m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${CYAN}${BOLD}"
echo "=========================================================="
echo " Configuring Aider for NVIDIA NIM (macOS / Linux)"
echo " Global config: $AIDER_CONF"
echo "=========================================================="
echo -e "${NC}"

# Read API Key and Model from .env if present
API_KEY=""
BASE_URL="https://integrate.api.nvidia.com/v1"
MODEL="nvidia/nemotron-3-ultra-550b-a55b"

if [ -f "$ENV_FILE" ]; then
  API_KEY=$(grep -E '^NVIDIA_API_KEY=' "$ENV_FILE" | cut -d '=' -f2- | tr -d ' "' || true)
  N_URL=$(grep -E '^NIM_BASE_URL=' "$ENV_FILE" | cut -d '=' -f2- | tr -d ' "' || true)
  N_MOD=$(grep -E '^NIM_MODEL=' "$ENV_FILE" | cut -d '=' -f2- | tr -d ' "' || true)
  [ -n "$N_URL" ] && BASE_URL="$N_URL"
  [ -n "$N_MOD" ] && MODEL="$N_MOD"
fi

# 1. Install model settings and metadata in ~/.
echo -e "▶ Copying NIM model settings to ${GREEN}$AIDER_SETTINGS${NC}..."
cp "$SRC_SETTINGS" "$AIDER_SETTINGS"

echo -e "▶ Copying NIM model metadata to ${GREEN}$AIDER_METADATA${NC}..."
cp "$SRC_METADATA" "$AIDER_METADATA"

# 2. Configure ~/.aider.conf.yml
if [ -f "$AIDER_CONF" ]; then
  BACKUP_FILE="${AIDER_CONF}.backup.$(date +%s)"
  cp "$AIDER_CONF" "$BACKUP_FILE"
  echo -e "  Created backup of existing config at: ${YELLOW}$BACKUP_FILE${NC}"
fi

cat << EOF > "$AIDER_CONF"
# ==============================================================================
# Aider Configuration for NVIDIA NIM
# Generated by nim-coding-assistants
# ==============================================================================

model: openai/$MODEL
openai-api-base: $BASE_URL
model-settings-file: $AIDER_SETTINGS
model-metadata-file: $AIDER_METADATA
show-model-warnings: false
stream: true
EOF

chmod 600 "$AIDER_CONF" 2>/dev/null || true
echo -e "${GREEN}✔ Created $AIDER_CONF successfully.${NC}"

# 3. Ensure global symlink for aider-nim
mkdir -p "$BIN_DIR"
chmod +x "$SCRIPT_DIR/scripts/mac-linux/aider-nim.sh"
ln -sf "$SCRIPT_DIR/scripts/mac-linux/aider-nim.sh" "$BIN_DIR/aider-nim"
echo -e "${GREEN}✔ Symlinked $BIN_DIR/aider-nim${NC}"

echo ""
echo -e "${GREEN}${BOLD}Aider is now fully configured for NVIDIA NIM!${NC}"
echo "You can launch Aider anytime using:"
echo -e "  ${CYAN}aider-nim${NC}             (Interactive launcher with model chooser & Architect mode)"
echo -e "  ${CYAN}aider-nim --architect${NC} (Nemotron 3 Ultra 550B plans, Super 120B applies diffs)"
echo -e "  ${CYAN}aider${NC}                 (Standard Aider CLI automatically picks up ~/.aider.conf.yml)"
echo ""
