<#
.SYNOPSIS
  Configure Aider for NVIDIA NIM on Windows (PowerShell)
#>

$ScriptDir = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$AiderConf = Join-Path $env:USERPROFILE ".aider.conf.yml"
$AiderSettings = Join-Path $env:USERPROFILE ".aider.model.settings.yml"
$AiderMetadata = Join-Path $env:USERPROFILE ".aider.model.metadata.json"

$SrcSettings = Join-Path $ScriptDir "config\aider.model.settings.yml"
$SrcMetadata = Join-Path $ScriptDir "config\aider.model.metadata.json"
$EnvFile = Join-Path $ScriptDir ".env"
$BinDir = Join-Path $env:USERPROFILE ".local\bin"

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host " Configuring Aider for NVIDIA NIM (Windows)" -ForegroundColor Cyan
Write-Host " Global config: $AiderConf" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# Read API Key and Model from .env if present
$ApiKey = ""
$BaseUrl = "https://integrate.api.nvidia.com/v1"
$Model = "nvidia/nemotron-3-ultra-550b-a55b"

if (Test-Path $EnvFile) {
    Get-Content $EnvFile | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith("#") -and $line.Contains("=")) {
            $parts = $line.Split("=", 2)
            $k = $parts[0].Trim()
            $v = $parts[1].Trim().Trim('"').Trim("'")
            if ($k -eq "NVIDIA_API_KEY") { $ApiKey = $v }
            if ($k -eq "NIM_BASE_URL") { $BaseUrl = $v }
            if ($k -eq "NIM_MODEL") { $Model = $v }
        }
    }
}

# 1. Install model settings and metadata in user profile
Write-Host "-> Copying NIM model settings to $AiderSettings..." -ForegroundColor Cyan
Copy-Item $SrcSettings $AiderSettings -Force

Write-Host "-> Copying NIM model metadata to $AiderMetadata..." -ForegroundColor Cyan
Copy-Item $SrcMetadata $AiderMetadata -Force

# 2. Configure .aider.conf.yml
if (Test-Path $AiderConf) {
    $timestamp = (Get-Date).ToString("yyyyMMdd_HHmmss")
    $backupFile = "$AiderConf.backup.$timestamp"
    Copy-Item $AiderConf $backupFile
    Write-Host "Created backup of existing config at: $backupFile" -ForegroundColor Yellow
}

# YAML paths should use forward slashes to avoid escape sequence issues
$settingsForward = $AiderSettings.Replace("\", "/")
$metadataForward = $AiderMetadata.Replace("\", "/")

$confLines = @(
    "# ==============================================================================",
    "# Aider Configuration for NVIDIA NIM",
    "# Generated by nim-coding-assistants",
    "# ==============================================================================",
    "",
    "model: openai/$Model",
    "openai-api-base: $BaseUrl",
    "model-settings-file: $settingsForward",
    "model-metadata-file: $metadataForward",
    "show-model-warnings: false",
    "stream: true"
)
$confContent = $confLines -join "`r`n"
Set-Content -Path $AiderConf -Value $confContent -Encoding UTF8
Write-Host "[OK] Created $AiderConf successfully." -ForegroundColor Green

# 3. Ensure global wrapper for aider-nim
if (-not (Test-Path $BinDir)) {
    New-Item -ItemType Directory -Path $BinDir -Force | Out-Null
}
$aiderCmd = Join-Path $BinDir "aider-nim.cmd"
$psAider = Join-Path $ScriptDir "scripts\windows\aider-nim.ps1"
$cmdLines = @(
    "@echo off",
    "powershell -ExecutionPolicy Bypass -File `"$psAider`" %*"
)
$cmdContent = $cmdLines -join "`r`n"
Set-Content -Path $aiderCmd -Value $cmdContent -Encoding ASCII
Write-Host "[OK] Registered $aiderCmd" -ForegroundColor Green

# Check user PATH for $BinDir
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($userPath -notlike "*$BinDir*") {
    [Environment]::SetEnvironmentVariable("Path", "$userPath;$BinDir", "User")
    Write-Host "[OK] Added $BinDir to User PATH." -ForegroundColor Green
}

Write-Host ""
Write-Host "Aider is now fully configured for NVIDIA NIM!" -ForegroundColor Green
Write-Host "You can launch Aider anytime using:"
Write-Host "  aider-nim             (Interactive launcher with model chooser & Architect mode)" -ForegroundColor Cyan
Write-Host "  aider-nim --architect (Nemotron 3 Ultra 550B plans, Super 120B applies diffs)" -ForegroundColor Cyan
Write-Host "  aider                 (Standard Aider CLI automatically picks up ~/.aider.conf.yml)" -ForegroundColor Cyan
Write-Host ""
